
import ROOT as rt
import argparse
from math import pi


parser = argparse.ArgumentParser("Prepare Prong CNN Images Training File")
parser.add_argument("-i", "--input", required=True, type=str, help="input prong image file")
parser.add_argument("-o", "--output", type=str, default="make_prong_sample_plots_output.root", help="output root file name")
parser.add_argument("-d", "--outDir", type=str, default="./", help="output file directory")
args = parser.parse_args()

f = rt.TFile(args.input)
t = f.Get("ImageTree")

h_el_trueEnergy = rt.TH1F("h_el_trueEnergy", "True Electron Energy for Electron Prongs", 100,0.,5000.)
h_el_trueTheta = rt.TH1F("h_el_trueTheta", "True Electron Beam Angle for Electron Prongs", 100,0.,180.)
h_el_purity = rt.TH1F("h_el_purity","Electron Prong Purity", 101,0,1.01)
h_el_completeness = rt.TH1F("h_el_completeness","Electron Prong Completeness", 81,0,1.0125)
h_el_purityVsSize = rt.TH2F("h_el_purityVsSize","Electron Prong Purity vs. Size", 100,0,4500, 101,0,1.01)
h_el_completenessVsSize = rt.TH2F("h_el_completenessVsSize","Electron Prong Completeness vs. Size", 100,0,4500, 81,0,1.0125)
h_el_purityVsEnergy = rt.TH2F("h_el_purityVsEnergy", "Electron Prong Purity vs True Energy", 100,0.,5000., 101,0,1.01)
h_el_completenessVsEnergy = rt.TH2F("h_el_completenessVsEnergy", "Electron Prong Completeness vs True Energy", 100,0.,5000., 81,0,1.0125)
h_el_completenessVsEdgeDist = rt.TH2F("h_el_completenessVsEdgeDist", "Electron Prong Completeness vs True Edge Distance", 100,-25.,125., 81,0,1.0125)
h_el_purityVsCompleteness = rt.TH2F("h_el_purityVsCompleteness", "Electron Prong Purity vs Completeness", 81,0,1.0125, 101,0,1.01)
h_el_bestOtherCompVsComp = rt.TH2F("h_el_bestOtherCompVsComp","Electron Prongs: Best Other Completeness vs. Completeness", 81,0,1.0125, 81,0,1.0125)

h_ph_trueEnergy = rt.TH1F("h_ph_trueEnergy", "True Photon Energy for Photon Prongs", 100,0.,2000.)
h_ph_trueTheta = rt.TH1F("h_ph_trueTheta", "True Photon Beam Angle for Photon Prongs", 100,0.,180.)
h_ph_purity = rt.TH1F("h_ph_purity","Photon Prong Purity", 101,0,1.01)
h_ph_completeness = rt.TH1F("h_ph_completeness","Photon Prong Completeness", 81,0,1.0125)
h_ph_purityVsSize = rt.TH2F("h_ph_purityVsSize","Photon Prong Purity vs. Size", 100,0,3000, 101,0,1.01)
h_ph_completenessVsSize = rt.TH2F("h_ph_completenessVsSize","Photon Prong Completeness vs. Size", 100,0,3000, 81,0,1.0125)
h_ph_purityVsEnergy = rt.TH2F("h_ph_purityVsEnergy", "Photon Prong Purity vs True Energy", 100,0.,2000., 101,0,1.01)
h_ph_completenessVsEnergy = rt.TH2F("h_ph_completenessVsEnergy", "Photon Prong Completeness vs True Energy", 100,0.,2000., 81,0,1.0125)
h_ph_completenessVsEdgeDist = rt.TH2F("h_ph_completenessVsEdgeDist", "Photon Prong Completeness vs True Edge Distance", 100,-25.,125., 81,0,1.0125)
h_ph_purityVsCompleteness = rt.TH2F("h_ph_purityVsCompleteness", "Photon Prong Purity vs Completeness", 81,0,1.0125, 101,0,1.01)
h_ph_bestOtherCompVsComp = rt.TH2F("h_ph_bestOtherCompVsComp","Photon Prongs: Best Other Completeness vs. Completeness", 81,0,1.0125, 81,0,1.0125)

h_mu_trueEnergy = rt.TH1F("h_mu_trueEnergy", "True Muon Energy for Muon Prongs", 100,0.,3500.)
h_mu_trueTheta = rt.TH1F("h_mu_trueTheta", "True Muon Beam Angle for Muon Prongs", 100,0.,180.)
h_mu_purity = rt.TH1F("h_mu_purity","Muon Prong Purity", 101,0,1.01)
h_mu_completeness = rt.TH1F("h_mu_completeness","Muon Prong Completeness", 81,0,1.0125)
h_mu_purityVsSize = rt.TH2F("h_mu_purityVsSize","Muon Prong Purity vs. Size", 100,0,2000, 101,0,1.01)
h_mu_completenessVsSize = rt.TH2F("h_mu_completenessVsSize","Muon Prong Completeness vs. Size", 100,0,2000, 81,0,1.0125)
h_mu_purityVsEnergy = rt.TH2F("h_mu_purityVsEnergy", "Muon Prong Purity vs True Energy", 100,0.,3500., 101,0,1.01)
h_mu_completenessVsEnergy = rt.TH2F("h_mu_completenessVsEnergy", "Muon Prong Completeness vs True Energy", 100,0.,3500., 81,0,1.0125)
h_mu_completenessVsEdgeDist = rt.TH2F("h_mu_completenessVsEdgeDist", "Muon Prong Completeness vs True Edge Distance", 100,-25.,125., 81,0,1.0125)
h_mu_purityVsCompleteness = rt.TH2F("h_mu_purityVsCompleteness", "Muon Prong Purity vs Completeness", 81,0,1.0125, 101,0,1.01)
h_mu_bestOtherCompVsComp = rt.TH2F("h_mu_bestOtherCompVsComp","Muon Prongs: Best Other Completeness vs. Completeness", 81,0,1.0125, 81,0,1.0125)

h_pi_trueEnergy = rt.TH1F("h_pi_trueEnergy", "True Pion Energy for Pion Prongs", 100,0.,2500.)
h_pi_trueTheta = rt.TH1F("h_pi_trueTheta", "True Pion Beam Angle for Pion Prongs", 100,0.,180.)
h_pi_purity = rt.TH1F("h_pi_purity","Pion Prong Purity", 101,0,1.01)
h_pi_completeness = rt.TH1F("h_pi_completeness","Pion Prong Completeness", 81,0,1.0125)
h_pi_purityVsSize = rt.TH2F("h_pi_purityVsSize","Pion Prong Purity vs. Size", 100,0,2000, 101,0,1.01)
h_pi_completenessVsSize = rt.TH2F("h_pi_completenessVsSize","Pion Prong Completeness vs. Size", 100,0,2000, 81,0,1.0125)
h_pi_purityVsEnergy = rt.TH2F("h_pi_purityVsEnergy", "Pion Prong Purity vs True Energy", 100,0.,2500., 101,0,1.01)
h_pi_completenessVsEnergy = rt.TH2F("h_pi_completenessVsEnergy", "Pion Prong Completeness vs True Energy", 100,0.,2500., 81,0,1.0125)
h_pi_completenessVsEdgeDist = rt.TH2F("h_pi_completenessVsEdgeDist", "Pion Prong Completeness vs True Edge Distance", 100,-25.,125., 81,0,1.0125)
h_pi_purityVsCompleteness = rt.TH2F("h_pi_purityVsCompleteness", "Pion Prong Purity vs Completeness", 81,0,1.0125, 101,0,1.01)
h_pi_bestOtherCompVsComp = rt.TH2F("h_pi_bestOtherCompVsComp","Pion Prongs: Best Other Completeness vs. Completeness", 81,0,1.0125, 81,0,1.0125)

h_pr_trueEnergy = rt.TH1F("h_pr_trueEnergy", "True Proton Energy for Proton Prongs", 100,700.,2500.)
h_pr_trueTheta = rt.TH1F("h_pr_trueTheta", "True Proton Beam Angle for Proton Prongs", 100,0.,180.)
h_pr_purity = rt.TH1F("h_pr_purity","Proton Prong Purity", 101,0,1.01)
h_pr_completeness = rt.TH1F("h_pr_completeness","Proton Prong Completeness", 81,0,1.0125)
h_pr_purityVsSize = rt.TH2F("h_pr_purityVsSize","Proton Prong Purity vs. Size", 100,0,2000, 101,0,1.01)
h_pr_completenessVsSize = rt.TH2F("h_pr_completenessVsSize","Proton Prong Completeness vs. Size", 100,0,2000, 81,0,1.0125)
h_pr_purityVsEnergy = rt.TH2F("h_pr_purityVsEnergy", "Proton Prong Purity vs True Energy", 100,700.,2500., 101,0,1.01)
h_pr_completenessVsEnergy = rt.TH2F("h_pr_completenessVsEnergy", "Proton Prong Completeness vs True Energy", 100,700.,2500., 81,0,1.0125)
h_pr_completenessVsEdgeDist = rt.TH2F("h_pr_completenessVsEdgeDist", "Proton Prong Completeness vs True Edge Distance", 100,-25.,125., 81,0,1.0125)
h_pr_purityVsCompleteness = rt.TH2F("h_pr_purityVsCompleteness", "Proton Prong Purity vs Completeness", 81,0,1.0125, 101,0,1.01)
h_pr_bestOtherCompVsComp = rt.TH2F("h_pr_bestOtherCompVsComp","Proton Prongs: Best Other Completeness vs. Completeness", 81,0,1.0125, 81,0,1.0125)

h_el_trueEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_el_trueEnergy.SetLineWidth(2)
h_el_trueTheta.GetXaxis().SetTitle("true angle with respect to beam (degrees)")
h_el_trueTheta.SetLineWidth(2)
h_el_purity.GetXaxis().SetTitle("purity")
h_el_purity.SetLineWidth(2)
h_el_completeness.GetXaxis().SetTitle("completeness")
h_el_completeness.SetLineWidth(2)
h_el_purityVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_el_purityVsSize.GetYaxis().SetTitle("purity")
h_el_completenessVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_el_completenessVsSize.GetYaxis().SetTitle("completeness")
h_el_purityVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_el_purityVsEnergy.GetYaxis().SetTitle("purity")
h_el_completenessVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_el_completenessVsEnergy.GetYaxis().SetTitle("completeness")
h_el_completenessVsEdgeDist.GetXaxis().SetTitle("true particle distance to detector edge (cm)")
h_el_completenessVsEdgeDist.GetYaxis().SetTitle("completeness")
h_el_purityVsCompleteness.GetXaxis().SetTitle("completeness")
h_el_purityVsCompleteness.GetYaxis().SetTitle("purity")
h_el_bestOtherCompVsComp.GetXaxis().SetTitle("completeness")
h_el_bestOtherCompVsComp.GetYaxis().SetTitle("best other completeness for true particle")

h_ph_trueEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_ph_trueEnergy.SetLineWidth(2)
h_ph_trueTheta.GetXaxis().SetTitle("true angle with respect to beam (degrees)")
h_ph_trueTheta.SetLineWidth(2)
h_ph_purity.GetXaxis().SetTitle("purity")
h_ph_purity.SetLineWidth(2)
h_ph_completeness.GetXaxis().SetTitle("completeness")
h_ph_completeness.SetLineWidth(2)
h_ph_purityVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_ph_purityVsSize.GetYaxis().SetTitle("purity")
h_ph_completenessVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_ph_completenessVsSize.GetYaxis().SetTitle("completeness")
h_ph_purityVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_ph_purityVsEnergy.GetYaxis().SetTitle("purity")
h_ph_completenessVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_ph_completenessVsEnergy.GetYaxis().SetTitle("completeness")
h_ph_completenessVsEdgeDist.GetXaxis().SetTitle("true particle distance to detector edge (cm)")
h_ph_completenessVsEdgeDist.GetYaxis().SetTitle("completeness")
h_ph_purityVsCompleteness.GetXaxis().SetTitle("completeness")
h_ph_purityVsCompleteness.GetYaxis().SetTitle("purity")
h_ph_bestOtherCompVsComp.GetXaxis().SetTitle("completeness")
h_ph_bestOtherCompVsComp.GetYaxis().SetTitle("best other completeness for true particle")

h_mu_trueEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_mu_trueEnergy.SetLineWidth(2)
h_mu_trueTheta.GetXaxis().SetTitle("true angle with respect to beam (degrees)")
h_mu_trueTheta.SetLineWidth(2)
h_mu_purity.GetXaxis().SetTitle("purity")
h_mu_purity.SetLineWidth(2)
h_mu_completeness.GetXaxis().SetTitle("completeness")
h_mu_completeness.SetLineWidth(2)
h_mu_purityVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_mu_purityVsSize.GetYaxis().SetTitle("purity")
h_mu_completenessVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_mu_completenessVsSize.GetYaxis().SetTitle("completeness")
h_mu_purityVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_mu_purityVsEnergy.GetYaxis().SetTitle("purity")
h_mu_completenessVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_mu_completenessVsEnergy.GetYaxis().SetTitle("completeness")
h_mu_completenessVsEdgeDist.GetXaxis().SetTitle("true particle distance to detector edge (cm)")
h_mu_completenessVsEdgeDist.GetYaxis().SetTitle("completeness")
h_mu_purityVsCompleteness.GetXaxis().SetTitle("completeness")
h_mu_purityVsCompleteness.GetYaxis().SetTitle("purity")
h_mu_bestOtherCompVsComp.GetXaxis().SetTitle("completeness")
h_mu_bestOtherCompVsComp.GetYaxis().SetTitle("best other completeness for true particle")

h_pi_trueEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_pi_trueEnergy.SetLineWidth(2)
h_pi_trueTheta.GetXaxis().SetTitle("true angle with respect to beam (degrees)")
h_pi_trueTheta.SetLineWidth(2)
h_pi_purity.GetXaxis().SetTitle("purity")
h_pi_purity.SetLineWidth(2)
h_pi_completeness.GetXaxis().SetTitle("completeness")
h_pi_completeness.SetLineWidth(2)
h_pi_purityVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_pi_purityVsSize.GetYaxis().SetTitle("purity")
h_pi_completenessVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_pi_completenessVsSize.GetYaxis().SetTitle("completeness")
h_pi_purityVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_pi_purityVsEnergy.GetYaxis().SetTitle("purity")
h_pi_completenessVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_pi_completenessVsEnergy.GetYaxis().SetTitle("completeness")
h_pi_completenessVsEdgeDist.GetXaxis().SetTitle("true particle distance to detector edge (cm)")
h_pi_completenessVsEdgeDist.GetYaxis().SetTitle("completeness")
h_pi_purityVsCompleteness.GetXaxis().SetTitle("completeness")
h_pi_purityVsCompleteness.GetYaxis().SetTitle("purity")
h_pi_bestOtherCompVsComp.GetXaxis().SetTitle("completeness")
h_pi_bestOtherCompVsComp.GetYaxis().SetTitle("best other completeness for true particle")

h_pr_trueEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_pr_trueEnergy.SetLineWidth(2)
h_pr_trueTheta.GetXaxis().SetTitle("true angle with respect to beam (degrees)")
h_pr_trueTheta.SetLineWidth(2)
h_pr_purity.GetXaxis().SetTitle("purity")
h_pr_purity.SetLineWidth(2)
h_pr_completeness.GetXaxis().SetTitle("completeness")
h_pr_completeness.SetLineWidth(2)
h_pr_purityVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_pr_purityVsSize.GetYaxis().SetTitle("purity")
h_pr_completenessVsSize.GetXaxis().SetTitle("max number of pixels in plane")
h_pr_completenessVsSize.GetYaxis().SetTitle("completeness")
h_pr_purityVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_pr_purityVsEnergy.GetYaxis().SetTitle("purity")
h_pr_completenessVsEnergy.GetXaxis().SetTitle("true energy (MeV)")
h_pr_completenessVsEnergy.GetYaxis().SetTitle("completeness")
h_pr_completenessVsEdgeDist.GetXaxis().SetTitle("true particle distance to detector edge (cm)")
h_pr_completenessVsEdgeDist.GetYaxis().SetTitle("completeness")
h_pr_purityVsCompleteness.GetXaxis().SetTitle("completeness")
h_pr_purityVsCompleteness.GetYaxis().SetTitle("purity")
h_pr_bestOtherCompVsComp.GetXaxis().SetTitle("completeness")
h_pr_bestOtherCompVsComp.GetYaxis().SetTitle("best other completeness for true particle")


rt.gStyle.SetOptStat(0)

cnv = rt.TCanvas("cnv","cnv")
t.Draw("trueEnergy >> h_el_trueEnergy","abs(pdg) == 11","EHIST")
t.Draw("trueTheta*(180./pi) >> h_el_trueTheta","abs(pdg) == 11","EHIST")
t.Draw("purity >> h_el_purity","abs(pdg) == 11","EHIST")
t.Draw("completeness >> h_el_completeness","abs(pdg) == 11","EHIST")
t.Draw("purity:max_plane_nPix >> h_el_purityVsSize","abs(pdg) == 11","COLZ")
t.Draw("completeness:max_plane_nPix >> h_el_completenessVsSize","abs(pdg) == 11","COLZ")
t.Draw("purity:trueEnergy >> h_el_purityVsEnergy","abs(pdg) == 11","COLZ")
t.Draw("completeness:trueEnergy >> h_el_completenessVsEnergy","abs(pdg) == 11","COLZ")
t.Draw("completeness:trueEdgeDist >> h_el_completenessVsEdgeDist","abs(pdg) == 11","COLZ")
t.Draw("purity:completeness >> h_el_purityVsCompleteness","abs(pdg) == 11","COLZ")
t.Draw("bestOtherComp:completeness >> h_el_bestOtherCompVsComp","abs(pdg) == 11","COLZ")
t.Draw("trueEnergy >> h_ph_trueEnergy","abs(pdg) == 22","EHIST")
t.Draw("trueTheta*(180./pi) >> h_ph_trueTheta","abs(pdg) == 22","EHIST")
t.Draw("purity >> h_ph_purity","abs(pdg) == 22","EHIST")
t.Draw("completeness >> h_ph_completeness","abs(pdg) == 22","EHIST")
t.Draw("purity:max_plane_nPix >> h_ph_purityVsSize","abs(pdg) == 22","COLZ")
t.Draw("completeness:max_plane_nPix >> h_ph_completenessVsSize","abs(pdg) == 22","COLZ")
t.Draw("purity:trueEnergy >> h_ph_purityVsEnergy","abs(pdg) == 22","COLZ")
t.Draw("completeness:trueEnergy >> h_ph_completenessVsEnergy","abs(pdg) == 22","COLZ")
t.Draw("completeness:trueEdgeDist >> h_ph_completenessVsEdgeDist","abs(pdg) == 22","COLZ")
t.Draw("purity:completeness >> h_ph_purityVsCompleteness","abs(pdg) == 22","COLZ")
t.Draw("bestOtherComp:completeness >> h_ph_bestOtherCompVsComp","abs(pdg) == 22","COLZ")
t.Draw("trueEnergy >> h_mu_trueEnergy","abs(pdg) == 13","EHIST")
t.Draw("trueTheta*(180./pi) >> h_mu_trueTheta","abs(pdg) == 13","EHIST")
t.Draw("purity >> h_mu_purity","abs(pdg) == 13","EHIST")
t.Draw("completeness >> h_mu_completeness","abs(pdg) == 13","EHIST")
t.Draw("purity:max_plane_nPix >> h_mu_purityVsSize","abs(pdg) == 13","COLZ")
t.Draw("completeness:max_plane_nPix >> h_mu_completenessVsSize","abs(pdg) == 13","COLZ")
t.Draw("purity:trueEnergy >> h_mu_purityVsEnergy","abs(pdg) == 13","COLZ")
t.Draw("completeness:trueEnergy >> h_mu_completenessVsEnergy","abs(pdg) == 13","COLZ")
t.Draw("completeness:trueEdgeDist >> h_mu_completenessVsEdgeDist","abs(pdg) == 13","COLZ")
t.Draw("purity:completeness >> h_mu_purityVsCompleteness","abs(pdg) == 13","COLZ")
t.Draw("bestOtherComp:completeness >> h_mu_bestOtherCompVsComp","abs(pdg) == 13","COLZ")
t.Draw("trueEnergy >> h_pi_trueEnergy","abs(pdg) == 211","EHIST")
t.Draw("trueTheta*(180./pi) >> h_pi_trueTheta","abs(pdg) == 211","EHIST")
t.Draw("purity >> h_pi_purity","abs(pdg) == 211","EHIST")
t.Draw("completeness >> h_pi_completeness","abs(pdg) == 211","EHIST")
t.Draw("purity:max_plane_nPix >> h_pi_purityVsSize","abs(pdg) == 211","COLZ")
t.Draw("completeness:max_plane_nPix >> h_pi_completenessVsSize","abs(pdg) == 211","COLZ")
t.Draw("purity:trueEnergy >> h_pi_purityVsEnergy","abs(pdg) == 211","COLZ")
t.Draw("completeness:trueEnergy >> h_pi_completenessVsEnergy","abs(pdg) == 211","COLZ")
t.Draw("completeness:trueEdgeDist >> h_pi_completenessVsEdgeDist","abs(pdg) == 211","COLZ")
t.Draw("purity:completeness >> h_pi_purityVsCompleteness","abs(pdg) == 211","COLZ")
t.Draw("bestOtherComp:completeness >> h_pi_bestOtherCompVsComp","abs(pdg) == 211","COLZ")
t.Draw("trueEnergy >> h_pr_trueEnergy","abs(pdg) == 2212","EHIST")
t.Draw("trueTheta*(180./pi) >> h_pr_trueTheta","abs(pdg) == 2212","EHIST")
t.Draw("purity >> h_pr_purity","abs(pdg) == 2212","EHIST")
t.Draw("completeness >> h_pr_completeness","abs(pdg) == 2212","EHIST")
t.Draw("purity:max_plane_nPix >> h_pr_purityVsSize","abs(pdg) == 2212","COLZ")
t.Draw("completeness:max_plane_nPix >> h_pr_completenessVsSize","abs(pdg) == 2212","COLZ")
t.Draw("purity:trueEnergy >> h_pr_purityVsEnergy","abs(pdg) == 2212","COLZ")
t.Draw("completeness:trueEnergy >> h_pr_completenessVsEnergy","abs(pdg) == 2212","COLZ")
t.Draw("completeness:trueEdgeDist >> h_pr_completenessVsEdgeDist","abs(pdg) == 2212","COLZ")
t.Draw("purity:completeness >> h_pr_purityVsCompleteness","abs(pdg) == 2212","COLZ")
t.Draw("bestOtherComp:completeness >> h_pr_bestOtherCompVsComp","abs(pdg) == 2212","COLZ")


h_el_trueEnergy.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_trueEnergy.png"))
h_el_trueTheta.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_trueTheta.png"))
h_el_purity.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_purity.png"))
h_el_completeness.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_completeness.png"))
h_el_purityVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_purityVsSize.png"))
h_el_completenessVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_completenessVsSize.png"))
h_el_purityVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_purityVsEnergy.png"))
h_el_completenessVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_completenessVsEnergy.png"))
h_el_completenessVsEdgeDist.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_completenessVsEdgeDist.png"))
h_el_purityVsCompleteness.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_purityVsCompleteness.png"))
h_el_bestOtherCompVsComp.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_el_bestOtherCompVsComp.png"))

h_ph_trueEnergy.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_trueEnergy.png"))
h_ph_trueTheta.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_trueTheta.png"))
h_ph_purity.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_purity.png"))
h_ph_completeness.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_completeness.png"))
h_ph_purityVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_purityVsSize.png"))
h_ph_completenessVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_completenessVsSize.png"))
h_ph_purityVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_purityVsEnergy.png"))
h_ph_completenessVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_completenessVsEnergy.png"))
h_ph_completenessVsEdgeDist.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_completenessVsEdgeDist.png"))
h_ph_purityVsCompleteness.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_purityVsCompleteness.png"))
h_ph_bestOtherCompVsComp.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_ph_bestOtherCompVsComp.png"))

h_mu_trueEnergy.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_trueEnergy.png"))
h_mu_trueTheta.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_trueTheta.png"))
h_mu_purity.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_purity.png"))
h_mu_completeness.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_completeness.png"))
h_mu_purityVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_purityVsSize.png"))
h_mu_completenessVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_completenessVsSize.png"))
h_mu_purityVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_purityVsEnergy.png"))
h_mu_completenessVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_completenessVsEnergy.png"))
h_mu_completenessVsEdgeDist.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_completenessVsEdgeDist.png"))
h_mu_purityVsCompleteness.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_purityVsCompleteness.png"))
h_mu_bestOtherCompVsComp.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_mu_bestOtherCompVsComp.png"))

h_pi_trueEnergy.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_trueEnergy.png"))
h_pi_trueTheta.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_trueTheta.png"))
h_pi_purity.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_purity.png"))
h_pi_completeness.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_completeness.png"))
h_pi_purityVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_purityVsSize.png"))
h_pi_completenessVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_completenessVsSize.png"))
h_pi_purityVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_purityVsEnergy.png"))
h_pi_completenessVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_completenessVsEnergy.png"))
h_pi_completenessVsEdgeDist.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_completenessVsEdgeDist.png"))
h_pi_purityVsCompleteness.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_purityVsCompleteness.png"))
h_pi_bestOtherCompVsComp.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pi_bestOtherCompVsComp.png"))

h_pr_trueEnergy.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_trueEnergy.png"))
h_pr_trueTheta.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_trueTheta.png"))
h_pr_purity.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_purity.png"))
h_pr_completeness.Draw("EHIST")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_completeness.png"))
h_pr_purityVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_purityVsSize.png"))
h_pr_completenessVsSize.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_completenessVsSize.png"))
h_pr_purityVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_purityVsEnergy.png"))
h_pr_completenessVsEnergy.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_completenessVsEnergy.png"))
h_pr_completenessVsEdgeDist.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_completenessVsEdgeDist.png"))
h_pr_purityVsCompleteness.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_purityVsCompleteness.png"))
h_pr_bestOtherCompVsComp.Draw("COLZ")
cnv.SaveAs(args.outDir+"/"+args.output.replace(".root","_pr_bestOtherCompVsComp.png"))


outFile = rt.TFile(args.outDir+"/"+args.output, "RECREATE")
h_el_trueEnergy.Write()
h_el_trueTheta.Write()
h_el_purity.Write()
h_el_completeness.Write()
h_el_purityVsSize.Write()
h_el_completenessVsSize.Write()
h_el_purityVsEnergy.Write()
h_el_completenessVsEnergy.Write()
h_el_completenessVsEdgeDist.Write()
h_el_purityVsCompleteness.Write()
h_el_bestOtherCompVsComp.Write()
h_ph_trueEnergy.Write()
h_ph_trueTheta.Write()
h_ph_purity.Write()
h_ph_completeness.Write()
h_ph_purityVsSize.Write()
h_ph_completenessVsSize.Write()
h_ph_purityVsEnergy.Write()
h_ph_completenessVsEnergy.Write()
h_ph_completenessVsEdgeDist.Write()
h_ph_purityVsCompleteness.Write()
h_ph_bestOtherCompVsComp.Write()
h_mu_trueEnergy.Write()
h_mu_trueTheta.Write()
h_mu_purity.Write()
h_mu_completeness.Write()
h_mu_purityVsSize.Write()
h_mu_completenessVsSize.Write()
h_mu_purityVsEnergy.Write()
h_mu_completenessVsEnergy.Write()
h_mu_completenessVsEdgeDist.Write()
h_mu_purityVsCompleteness.Write()
h_mu_bestOtherCompVsComp.Write()
h_pi_trueEnergy.Write()
h_pi_trueTheta.Write()
h_pi_purity.Write()
h_pi_completeness.Write()
h_pi_purityVsSize.Write()
h_pi_completenessVsSize.Write()
h_pi_purityVsEnergy.Write()
h_pi_completenessVsEnergy.Write()
h_pi_completenessVsEdgeDist.Write()
h_pi_purityVsCompleteness.Write()
h_pi_bestOtherCompVsComp.Write()
h_pr_trueEnergy.Write()
h_pr_trueTheta.Write()
h_pr_purity.Write()
h_pr_completeness.Write()
h_pr_purityVsSize.Write()
h_pr_completenessVsSize.Write()
h_pr_purityVsEnergy.Write()
h_pr_completenessVsEnergy.Write()
h_pr_completenessVsEdgeDist.Write()
h_pr_purityVsCompleteness.Write()
h_pr_bestOtherCompVsComp.Write()


#for i in range(t.GetEntries()):
#
#  if i % 10000 == 0:
#    print("reached entry %i of %i"%(i, t.GetEntries()))
#
#  t.GetEntry(i)
#
#  nPix = t.plane0_nPix
#  if t.plane1_nPix > nPix:
#    nPix = t.plane1_nPix
#  if t.plane2_nPix > nPix:
#    nPix = t.plane2_nPix
#
#  if abs(t.pdg) == 11:
#    h_el_trueEnergy.Fill(t.trueEnergy)
#    h_el_trueTheta.Fill(t.trueTheta*(180./pi))
#    h_el_purity.Fill(t.purity)
#    h_el_completeness.Fill(t.completeness)
#    h_el_purityVsSize.Fill(nPix, t.purity)
#    h_el_completenessVsSize.Fill(nPix, t.completeness)
#
#  if abs(t.pdg) == 22:
#    h_ph_trueEnergy.Fill(t.trueEnergy)
#    h_ph_trueTheta.Fill(t.trueTheta*(180./pi))
#    h_ph_purity.Fill(t.purity)
#    h_ph_completeness.Fill(t.completeness)
#    h_ph_purityVsSize.Fill(nPix, t.purity)
#    h_ph_completenessVsSize.Fill(nPix, t.completeness)
#
#  if abs(t.pdg) == 13:
#    h_mu_trueEnergy.Fill(t.trueEnergy)
#    h_mu_trueTheta.Fill(t.trueTheta*(180./pi))
#    h_mu_purity.Fill(t.purity)
#    h_mu_completeness.Fill(t.completeness)
#    h_mu_purityVsSize.Fill(nPix, t.purity)
#    h_mu_completenessVsSize.Fill(nPix, t.completeness)
#
#  if abs(t.pdg) == 211:
#    h_pi_trueEnergy.Fill(t.trueEnergy)
#    h_pi_trueTheta.Fill(t.trueTheta*(180./pi))
#    h_pi_purity.Fill(t.purity)
#    h_pi_completeness.Fill(t.completeness)
#    h_pi_purityVsSize.Fill(nPix, t.purity)
#    h_pi_completenessVsSize.Fill(nPix, t.completeness)
#
#  if abs(t.pdg) == 2212:
#    h_pr_trueEnergy.Fill(t.trueEnergy)
#    h_pr_trueTheta.Fill(t.trueTheta*(180./pi))
#    h_pr_purity.Fill(t.purity)
#    h_pr_completeness.Fill(t.completeness)
#    h_pr_purityVsSize.Fill(nPix, t.purity)
#    h_pr_completenessVsSize.Fill(nPix, t.completeness)
#
#
#h_el_trueEnergy.Write()
#h_el_trueTheta.Write()
#h_el_purity.Write()
#h_el_completeness.Write()
#h_el_purityVsSize.Write()
#h_el_completenessVsSize.Write()
#
#h_ph_trueEnergy.Write()
#h_ph_trueTheta.Write()
#h_ph_purity.Write()
#h_ph_completeness.Write()
#h_ph_purityVsSize.Write()
#h_ph_completenessVsSize.Write()
#
#h_mu_trueEnergy.Write()
#h_mu_trueTheta.Write()
#h_mu_purity.Write()
#h_mu_completeness.Write()
#h_mu_purityVsSize.Write()
#h_mu_completenessVsSize.Write()
#
#h_pi_trueEnergy.Write()
#h_pi_trueTheta.Write()
#h_pi_purity.Write()
#h_pi_completeness.Write()
#h_pi_purityVsSize.Write()
#h_pi_completenessVsSize.Write()
#
#h_pr_trueEnergy.Write()
#h_pr_trueTheta.Write()
#h_pr_purity.Write()
#h_pr_completeness.Write()
#h_pr_purityVsSize.Write()
#h_pr_completenessVsSize.Write()


